Issue/30 display own courses
HPI-de/hpi-android pull request #51
Opened 2019-06-16 18:43 UTC by ctiedt

**Fixes: #30 **

**Checklist**

**Changes**

Implemented the basic data structure for courses in the app

2019-06-17 20:53 UTC, Nsgr requested changes

2019-06-17 20:53 UTC, Nsgr commented on course/src/main/res/layout/item_course.xml
> +    <com.google.android.material.card.MaterialCardView
This card view should not be here, it causes a white background (in contrast to the mock-up)

2019-06-17 20:53 UTC, Nsgr commented on course/src/main/res/layout/item_course.xml
> +                android:paddingStart="@dimen/space_m"
Please change the padding here, instead of the text view having such a big top padding, please set the padding for the list element itself so when the text is loading and a grey box is shown, that grey box is only where the text should be and not reaching to the top of the linear Layout

2019-06-17 20:53 UTC, Nsgr commented on course/src/main/res/layout/item_course.xml
> +        <LinearLayout
The list items have a little bit too much of a height, please take a look around here: https://material.io/design/components/lists.html#specs

2019-06-19 13:22 UTC, JonasWanke approved these changes

2019-06-19 15:50 UTC, Nsgr approved these changes

2019-06-19 16:26 UTC, merged